### ISSUE TITLE
[Q] Request object passed to roles function

### ISSUE THREAD

**Issue by timoweiss** [charlesread/hapi-acl-auth#3]
Hi, first of all: thanks for this project. I really like how the problem is addressed here.

I'm currently working on a project with needs to handle dynamic roles.
Therefore, I need to resolve the allowed roles for a specific route during a request dynamically based on the credentials object.
I'm wondering if you would accept a PR where the [roles function](https://github.com/charlesread/hapi-acl-auth/blob/master/lib/authorization.js#L30) is extended with the request object as param here?

Thanks for your time!

**Comment by charlesread** [comment]
Hey sorry for they delay, feel free to submit anything you like!

**Comment by charlesread** [comment]
@timoweiss , this feature has been added in the 1.0.1 release.
