### ISSUE TITLE
Hapi v17 support

### ISSUE THREAD

**Issue by toddhickerson** [charlesread/hapi-acl-auth#5]
I am looking for a roles plugin that supports hapi v17. Are you planning to update this plugin to support it?

**Comment by charlesread** [comment]
Hi @toddhickerson , I am planning on updating it, hopefully next week.  Pull requests are always welcomed.

**Comment by charlesread** [comment]
@toddhickerson , check out the `hapi17` branch of `hapi-acl-auth`, I have to finish refactoring the tests, once I do I'll publish as a major release.  Should be sometime this weekend, maybe tonight.

**Comment by charlesread** [comment]
Version 1.x, with full support for Hapi 17.x and Node 8.x, has now been published.

**Comment by toddhickerson** [comment]
That's awesome! Thank you, Charles! I'll check it out soon.
